from django.db import models

# Models are stored in Supabase
'''
create table public.teams (
  id integer generated by default as identity not null,
  name text not null,
  join_code character varying not null,
  admin_id uuid not null default gen_random_uuid (),
  session_creation_access text null default 'staff_only',
  created_at timestamp with time zone null,
  updated_at timestamp with time zone null,
  constraint teams_pkey primary key (id),
  constraint teams_join_code_key unique (join_code),
  constraint teams_admin_id_fkey foreign KEY (admin_id) references profiles (id)
) TABLESPACE pg_default;
'''
