-- PitchEye Supabase bootstrap schema
-- Run this in the Supabase SQL editor for a fresh local setup.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'user_role'
  ) then
    create type public.user_role as enum ('viewer', 'coach', 'admin', 'player', 'parent');
  end if;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text,
  role public.user_role not null default 'viewer',
  team_id integer,
  created_at timestamptz default now()
);

create table if not exists public.teams (
  id integer generated by default as identity primary key,
  name text not null,
  join_code varchar not null unique,
  admin_id uuid not null references public.profiles(id),
  session_creation_access text not null default 'staff_only',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.teams
  drop constraint if exists teams_session_creation_access_check;

alter table public.teams
  add constraint teams_session_creation_access_check
  check (session_creation_access in ('owner_only', 'staff_only', 'all_members'));

alter table public.profiles
  drop constraint if exists profiles_team_id_fkey;

alter table public.profiles
  add constraint profiles_team_id_fkey
  foreign key (team_id) references public.teams(id) on delete set null;

create table if not exists public.games (
  id integer generated by default as identity primary key,
  session_code varchar(10) not null unique,
  qr_code_url text,
  title text,
  game_time timestamptz,
  created_by uuid not null references public.profiles(id) on delete cascade,
  is_synchronized boolean not null default false,
  is_processed boolean not null default false,
  created_at timestamptz default now(),
  ended_at timestamptz
);

create table if not exists public.video_clips (
  id integer generated by default as identity primary key,
  game_id integer not null references public.games(id) on delete cascade,
  uploaded_by uuid not null references public.profiles(id) on delete cascade,
  video_url text not null,
  file_size bigint not null,
  duration double precision,
  resolution varchar(20),
  device_id varchar(100) not null,
  device_name varchar(100),
  recorded_at timestamptz not null,
  time_offset double precision,
  start_time double precision,
  end_time double precision,
  quality_score integer,
  camera_angle text,
  caption text not null default '',
  tagged_players jsonb not null default '[]'::jsonb,
  is_processed boolean not null default false,
  uploaded_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint video_clips_quality_score_check
    check (quality_score is null or (quality_score >= 1 and quality_score <= 100))
);

create table if not exists public.comments (
  id integer generated by default as identity primary key,
  video_id integer not null references public.video_clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  parent_comment_id integer references public.comments(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.livestreams (
  id integer generated by default as identity primary key,
  session_code varchar(10) not null,
  game_id integer not null references public.games(id) on delete cascade,
  stream_key text not null unique,
  host_user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'live',
  rtmp_url text,
  hls_url text,
  started_at timestamptz default now(),
  ended_at timestamptz,
  constraint livestreams_status_check
    check (status in ('live', 'ended'))
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('match-videos', 'match-videos', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('qr-codes', 'qr-codes', false)
on conflict (id) do nothing;
